Attributes<-read.table("Census 2010 DP1 DP2 and DP3 - Extracted Attributes.csv", header=T, sep=',')
fatality<-read.table("FatalititesDatasetByYear.csv", header=T, sep=',')
F10 <- fatality[, c(1,12)]
data10<-merge(F10, Attributes, by="State")
rate<-data10$Y2010/data10$Total.population
model<-lm(rate~data10$Total.population+data10$Median.age..years.+ data10$Percent.with.no.bachelor.degree.or.higher+data10$Percent.Never.Married+data10$Percent.Disabled+data10$Median.family.income..dollars.+data10$Percent.Unemployed)
summary(model)
cor(rate,data10$Total.population)
cor(rate,data10$Median.age..years.)
cor(rate,data10$Percent.with.no.bachelor.degree.or.higher)
cor(rate,data10$Percent.Never.Married)
cor(rate,data10$Percent.Disabled)
cor(rate,data10$Median.family.income..dollars.)
cor(rate,data10$Percent.Unemployed)
cor(data10$Total.population,data10$Percent.Unemployed)
cor(data10$Total.population,data10$Median.age..years.)
cor(data10$Total.population,data10$Percent.with.no.bachelor.degree.or.higher)
cor(data10$Total.population,data10$Percent.Never.Married)
cor(data10$Total.population,data10$Percent.Disabled)
cor(data10$Total.population,data10$Median.family.income..dollars.)
cor(data10$Median.age..years.,data10$Percent.with.no.bachelor.degree.or.higher)
cor(data10$Median.age..years.,data10$Percent.Never.Married)
cor(data10$Median.age..years.,data10$Percent.Disabled)
cor(data10$Median.age..years.,data10$Median.family.income..dollars.)
cor(data10$Median.age..years.,data10$Percent.Unemployed)
cor(data10$Percent.with.no.bachelor.degree.or.higher,data10$Percent.Never.Married)
cor(data10$Percent.with.no.bachelor.degree.or.higher,data10$Percent.Disabled)
cor(data10$Percent.with.no.bachelor.degree.or.higher,data10$Median.family.income..dollars.)
cor(data10$Percent.with.no.bachelor.degree.or.higher,data10$Percent.Unemployed)
cor(data10$Percent.Never.Married,data10$Percent.Disabled)
cor(data10$Percent.Never.Married,data10$Median.family.income..dollars.)
cor(data10$Percent.Never.Married,data10$Percent.Unemployed)
cor(data10$Percent.Disabled,data10$Median.family.income..dollars.)
cor(data10$Percent.Disabled,data10$Percent.Unemployed)
cor(data10$Median.family.income..dollars.,data10$Percent.Unemployed)

