Attributes<-read.table("Census 2000 DP1 DP2 and DP3 - Extracted Attributes.csv", header=T, sep=',')
fatality<-read.table("FatalititesDatasetByYear.csv", header=T, sep=',')
F00 <- fatality[, c(1,2)]
data00<-merge(F00, Attributes, by="State")
rate<-data00$Y2000/data00$Total.population
model<-lm(rate~data00$Total.population+data00$Median.age..years.+ data00$Percent.with.no.bachelor.degree.or.higher+data00$Percent.Never.Married+data00$Percent.Disabled+data00$Median.family.income..dollars.+data00$Percent.Unemployed)
summary(model)
cor(rate,data00$Total.population)
cor(rate,data00$Median.age..years.)
cor(rate,data00$Percent.with.no.bachelor.degree.or.higher)
cor(rate,data00$Percent.Never.Married)
cor(rate,data00$Percent.Disabled)
cor(rate,data00$Median.family.income..dollars.)
cor(rate,data00$Percent.Unemployed)
cor(data00$Total.population,data00$Percent.Unemployed)
cor(data00$Total.population,data00$Median.age..years.)
cor(data00$Total.population,data00$Percent.with.no.bachelor.degree.or.higher)
cor(data00$Total.population,data00$Percent.Never.Married)
cor(data00$Total.population,data00$Percent.Disabled)
cor(data00$Total.population,data00$Median.family.income..dollars.)
cor(data00$Median.age..years.,data00$Percent.with.no.bachelor.degree.or.higher)
cor(data00$Median.age..years.,data00$Percent.Never.Married)
cor(data00$Median.age..years.,data00$Percent.Disabled)
cor(data00$Median.age..years.,data00$Median.family.income..dollars.)
cor(data00$Median.age..years.,data00$Percent.Unemployed)
cor(data00$Percent.with.no.bachelor.degree.or.higher,data00$Percent.Never.Married)
cor(data00$Percent.with.no.bachelor.degree.or.higher,data00$Percent.Disabled)
cor(data00$Percent.with.no.bachelor.degree.or.higher,data00$Median.family.income..dollars.)
cor(data00$Percent.with.no.bachelor.degree.or.higher,data00$Percent.Unemployed)
cor(data00$Percent.Never.Married,data00$Percent.Disabled)
cor(data00$Percent.Never.Married,data00$Median.family.income..dollars.)
cor(data00$Percent.Never.Married,data00$Percent.Unemployed)
cor(data00$Percent.Disabled,data00$Median.family.income..dollars.)
cor(data00$Percent.Disabled,data00$Percent.Unemployed)
cor(data00$Median.family.income..dollars.$Percent.Unemployed)
cor(data00$Median.family.income..dollars.,data00$Percent.Unemployed)

